In [34]:
import os
import pandas as pd
from dask import dataframe as dd

In [24]:
PATH_DATA = '../data'

In [26]:
tr_mcc_codes = pd.read_csv(os.path.join(PATH_DATA, 'mcc_codes.csv'), sep=';', index_col='mcc_code')
tr_types = pd.read_csv(os.path.join(PATH_DATA, 'trans_types.csv'), sep=';', index_col='trans_type')

transactions = pd.read_csv(os.path.join(PATH_DATA, 'transactions.csv'), index_col='client_id', chunksize=10000)
gender_train = pd.read_csv(os.path.join(PATH_DATA, 'train.csv'), index_col='client_id')
gender_test = pd.read_csv(os.path.join(PATH_DATA, 'test.csv'), index_col='client_id')
# transactions_train = transactions.join(gender_train, how='inner')
# transactions_test = transactions.join(gender_test, how='inner')

In [47]:
dask_df = dd.read_csv(os.path.join(PATH_DATA, 'transactions.csv')).compute()

In [49]:
dask_df

,client_id,trans_time,mcc_code,trans_type,amount,term_id,trans_city
0,d1bbbc9a0e0410d3cf12a3d2f44f3450,35 08:24:41,4829,2370,-1808.56,NaN,Tver
1,81c7349f7bdcb661bc7d5f5f0fdac6aa,351 13:27:15,6011,7010,7954.51,442207,Kazan
2,fc0c7c937f139bd6d1c5b5d0a0023dd3,150 16:03:59,6011,2010,-12293.56,NaN,Khabarovsk
3,3495487d5beaa5caaa0682fddc38379a,373 11:54:12,6010,7070,49.52,888987,Kaliningrad
4,07e279042b1da23710fa2f65034d30b9,340 13:11:45,6010,7070,45.29,888918,Saint Petersburg
...,...,...,...,...,...,...,...
890939,e91858185ae43cf3970220748893a01b,328 13:45:38,6010,7070,227.40,888907,Penza
890940,429b6c8255f13bdb506fdbd6e342ccb1,10 19:22:35,4814,1030,-1084.44,NaN,Khabarovsk
890941,9443b6a0d948cf368d8d72eb295bdfdf,167 23:59:15,5411,1110,-569.20,NaN,Tver
890942,1be75d38ad89c0f2b4d85b95f0fd8069,101 23:59:03,5814,1110,-71.43,NaN,Vladivostok
890943,8d69e4ecae4b509d528b9a0168f749d0,148 19:12:04,6010,7070,50.92,NaN,Kazan